name: Heirloom
description: A GitHub Action that prevents parent issues from being marked as stale by checking for recent activity on their sub-issues.
author: InfiniteSkyAI
branding:
  icon: 'package'
  color: 'blue'

inputs:
  github-token:
    description: 'A GitHub Personal Access Token (PAT) with read:org and repo scopes.'
    required: true
  repo-owner:
    description: 'The owner of the repository.'
    required: false
    default: ${{ github.repository_owner }}
  repo-name:
    description: 'The name of the repository.'
    required: false
    default: ${{ github.event.repository.name }}
  parent-issue-labels:
    description: 'A comma-separated list of labels to identify parent issues.'
    required: false
    default: ''
  parent-issue-types:
    description: 'A comma-separated list of issue types to identify parent issues (e.g., "EPIC").'
    required: false
    default: ''
  days-threshold:
    description: 'The number of days of inactivity on a child issue to consider it "stale."'
    required: false
    default: '30'
  update-message:
    description: 'The comment to add to parent issues to reset their stale timer.'
    required: false
    default: "🤖 Heirloom bot is keeping this epic fresh due to recent child issue activity."
  ignore-labels:
    description: 'Comma-separated list of labels which, when present on a child issue, should be treated as non-activity (case-insensitive). Defaults to "stale".'
    required: false
    default: 'stale'
  update-all-ancestors:
    description: 'When true, Heirloom will find all active issues and update all of their ancestors in the hierarchy. This overrides parent-issue-labels and parent-issue-types.'
    required: false
    default: 'false'

runs:
  using: 'docker'
  image: 'Dockerfile'
