name: 'Heirloom'
description: 'Prevents parent issues from being marked as stale if any of their sub-issues are active.'
author: 'Your GitHub Username'

inputs:
  repo-owner:
    description: 'The owner of the repository.'
    required: true
    default: ${{ github.repository_owner }}
  repo-name:
    description: 'The name of the repository.'
    required: true
    default: ${{ github.event.repository.name }}
  parent-issue-labels:
    description: 'A comma-separated list of labels to identify parent issues (e.g., epic, story).'
    required: false
    default: 'epic,story'
  days-threshold:
    description: 'The number of days of inactivity on a child issue to consider it "stale".'
    required: false
    default: '30'
  update-message:
    description: 'The comment to add to parent issues to reset their stale timer.'
    required: false
    default: "🤖 This parent issue has been updated due to recent activity on a child issue."

runs:
  using: 'node20'
  main: 'dist/index.js' # This points to the compiled JavaScript file.
