name: 'Heirloom'
description: 'Prevents parent issues from being marked as stale if any of their sub-issues are active.'
author: 'qodfathr'

inputs:
  github-token:
    description: 'Token to authenticate with the GitHub API. This should be a PAT with read/write access to issues and projects.'
    required: true
  repo-owner:
    description: 'The owner of the repository.'
    required: false
    default: ${{ github.repository_owner }}
  repo-name:
    description: 'The name of the repository.'
    required: false
    default: ${{ github.event.repository.name }}
  parent-issue-labels:
    description: 'A comma-separated list of labels to identify parent issues (e.g., epic, story).'
    required: false
    default: 'epic,story'
  days-threshold:
    description: 'The number of days of inactivity on a child issue to consider it "stale".'
    required: false
    default: '30'
  update-message:
    description: 'The comment to add to parent issues to reset their stale timer.'
    required: false
    default: "🤖 This parent issue has been updated due to recent activity on a child issue."

runs:
  using: 'docker'
  image: 'Dockerfile'
